fixes `encode` failure when provided an already (validly) truncated digest
multiformats/ex_multihash pull request #10
Opened 2019-05-12 01:47 UTC by sunny-g

2019-05-15 16:15 UTC, zabirauf commented
Thanks for the PR. I'll take a look at it.

2019-05-16 05:15 UTC, zabirauf requested changes

2019-05-16 05:15 UTC, zabirauf commented on lib/multihash.ex
> +      digest_len when digest_len >= trunc_length -> :ok
This should also check for case when `trunc_length` is not `:default`. As if it is default then this check shouldn't pass.

```
digest_len when trunc_length !== :default and digest_len >= trunc_length -> :ok
```
```

2019-05-29 21:16 UTC, sunny-g commented on lib/multihash.ex
> +      digest_len when digest_len >= trunc_length -> :ok
Good call, will add it.

2019-05-30 17:11 UTC, merged